Repositorio_3/blog/apps/noticias/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'noticias'

urlpatterns = [
    path('', views.ListarNoticias, name='listar'),
    path('detalle/<int:pk>', views.DetalleNoticia, name='detalle'),
    path('addNoticia', views.AddNoticia, name='addnoticia'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Repositorio_3/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name='home'),
    path('nosotros/', views.Nosotros, name='nosotros'),
    path('noticias/', include('apps.noticias.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
        
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Repositorio_3/blog/apps/noticias/models.py
from django.db import models
from apps.usuarios.models import Usuario

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre
    

class Noticia(models.Model):
    titulo = models.CharField(max_length=50) # = VARCHAR | max_length longitud max
    resumen = models.CharField(max_length=200, null=True)
    contenido = models.TextField()
    #imagen requiere la libreria pillow
    imagenes = models.ImageField(upload_to='noticias')
    fecha_publicacion = models.DateTimeField(auto_now_add=True)
    categoria_noticia = models.ForeignKey(Categoria, on_delete= models.SET_NULL, null=True) # models.CASCADE
    autor = models.ForeignKey(Usuario, on_delete=models.CASCADE, default=Usuario.objects.get(is_superuser=True).pk)

    def __str__(self):
        return self.titulo
    
class Comentario(models.Model):
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE, related_name='comentarios')
    contenido = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    usuario = models.CharField(max_length=50)

    def __str__(self):
        return self.contenido


Repositorio_3/blog/apps/noticias/forms.py
from django import forms
from .models import Noticia, Comentario

class NoticiaForm(forms.ModelForm):

    class Meta:
        model = Noticia
        fields = [
            'titulo',
            'resumen',
            'contenido',
            'imagenes',
            'categoria_noticia',
        ]

class ComentarioForm(forms.ModelForm):

    class Meta:
        model = Comentario
        fields = [
            'contenido',
        ]
        exclude = ['usuario']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)

        super(ComentarioForm, self).__init__(*args, **kwargs)
        if user:
            self.instance.usuario = user.username    

Repositorio_3/blog/apps/noticias/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from .models import Noticia, Categoria
from .forms import NoticiaForm, ComentarioForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def ListarNoticias(request):
    contexto = {}
    id_categoria = request.GET.get("id", None)
    antiguedad = request.GET.get("antiguedad", None)
    orden = request.GET.get("orden", None)

    n = Noticia.objects.all()

    if id_categoria:
        n = n.filter(categoria_noticia=id_categoria)

    if antiguedad == "asc":
        n = n.order_by('fecha_publicacion')
    elif antiguedad == "desc":
        n = n.order_by('-fecha_publicacion')

    if orden == "asc":
        n = n.order_by('titulo')
    elif orden == "desc":
        n = n.order_by('-titulo')

    contexto = {
        'noticias': n,
        'categorias': Categoria.objects.all(),
    }

    return render(request, 'noticias/listar.html', contexto)


    '''contexto = {}
    id_categoria = request.GET.get("id", None)

    if id_categoria:
        n = Noticia.objects.filter(categoria_noticia = id_categoria)
    else:    
        n = Noticia.objects.all() # SELECT * FROM NOTICIAS
    
    # filtrar por antiguedad asc
        antiguedad_asc = request.GET.get("antiguedad_asc")
        if antiguedad_asc:
            n = Noticia.objects.all().order_by('fecha_publicacion') #ordena por fecha

    # filtrar por antiguedad desc
        antiguedad_desc = request.GET.get("antiguedad_desc")
        if antiguedad_desc:
            n = Noticia.objects.all().order_by('-fecha_publicacion') #ordena por fecha

    # filtrar por orden alfabetico asc
        orden_asc = request.GET.get("orden_asc")
        if orden_asc:
            n = Noticia.objects.all().order_by('titulo') #ordena por titulo

     # filtrar por orden alfabetico desc
        orden_desc = request.GET.get("orden_desc")
        if orden_desc:
         n = Noticia.objects.all().order_by('-titulo') #ordena por titulo


    cat = Categoria.objects.all().order_by('nombre') #ORDENA POR NOMBRE
    contexto['noticias'] = n
    contexto['categorias'] = cat

    return render (request, 'noticias/listar.html', contexto)'''

'''def DetalleNoticia(request, pk):
    contexto = {}

    n = Noticia.objects.get(pk = pk) # SELECT * FROM NOTICIAS WHERE id = 1
    contexto['noticias'] = n

    #BORRAR NOTICIA
    if request.method == 'POST' and 'delete_noticia' in request.POST:
        n.delete()
        return redirect('noticias:listar')
    
    return render (request, 'noticias/detalle.html', contexto)'''

#DETALE NOTICIAS CON COMENTARIOS INCLUIDOS

def DetalleNoticia(request, pk):
    contexto = {}

    n = Noticia.objects.get(pk = pk) # SELECT * FROM NOTICIAS WHERE id = 1
    contexto['noticias'] = n

    c = n.comentarios.all()
    contexto['comentarios'] = c

    #BORRAR NOTICIA
    if request.method == 'POST' and 'delete_noticia' in request.POST:
        n.delete()
        return redirect('noticias:listar')
    
    #CREAR COMENTARIO
    if request.method == 'POST' and 'add_comentario' in request.POST:
       form = ComentarioForm(request.POST)
       if form.is_valid():
                comentario = form.save(commit=False)
                comentario.usuario = request.user
                form.save()
                return redirect('noticia:detalle', pk=pk)
    else:
        form = NoticiaForm()


    return render (request, 'noticias/detalle.html', contexto)

    

@login_required
def AddNoticia(request):
    if request.method == 'POST':
        form = NoticiaForm(request.POST or None, request.FILES) ##Request files es para las imagenes

        if form.is_valid():
            noticia = form.save(commit=False)
            noticia.autor = request.user
            form.save()
            return redirect('home')
    else:
        form = NoticiaForm()
    
    return render (request, 'noticias/addNoticia.html', {'form':form})

Repositorio_3/blog/templates/noticias/addNoticia.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}Noticias{% endblock titulo %}
{% block contenido %}
    <h2>Crea una noticia</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
{% endblock contenido %}


Repositorio_3/blog/templates/noticias/detalle.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}Noticias{% endblock titulo %}
{% block contenido %}
    <h2>Mi noticia detallada</h2>
    <div class="noti">
        <img src="{{noticias.imagenes.url}}" width="40%">
        <h3>{{noticias.titulo}}</h3>
        <p>{{noticias.contenido}}</p>       
        <p>{{noticias.fecha_publicacion}}</p>
        <p>{{noticias.categoria_noticia}}</p>
        <p>Autor: {{noticias.autor}}</p>
        {% if user.is_authenticated and noticias.autor == user %}
            <form method="POST" action="{% url 'noticias:detalle' pk=noticias.pk %}">
                {% csrf_token %}
                <button type="submit" name="delete_noticia">BORRAR</button>
            </form>
        {% endif %}  
        <br>
        <a href="{% url 'noticias:listar' %}">VOLVER</a>
    </div>

{% endblock contenido %}

Repositorio_3/blog/templates/noticias/listar.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}Noticias{% endblock titulo %}
{% block contenido %}
    <h2>aca estan mis noticias !</h2>
    <form method="get" action="{% url 'noticias:listar'%}">
        <select name="id">
            <option value="">Todas</option>
            {% for cat in categorias %}
                <option value="{{cat.pk}}">{{cat.nombre}}</option>
            {% endfor %}
        </select>
        
        <select name="antiguedad">
            <option value="">Ordenar por Antigüedad</option>
            <option value="asc">Más antiguas primero</option>
            <option value="desc">Más recientes primero</option>
        </select>
        
        <select name="orden">
            <option value="">Ordenar alfabéticamente</option>
            <option value="asc">A - Z</option>
            <option value="desc">Z - A</option>
        </select>
        
        <input type="submit" value="Filtrar">
    </form>    
    {% for noticia in noticias %}
        <h3><a href="{% url 'noticias:detalle' noticia.pk %}">Titulo: {{noticia.titulo}}</a></h3>
        <img src="{{noticia.imagenes.url}}" width="10%">
        <br>
    {% endfor %}

{% endblock contenido %}